// Generated by CoffeeScript 1.9.3
var App, React;

React = require("react");

App = require("./components/layout/App");

require("./assets/vendor/bootstrap/stylesheets/_bootstrap.scss");

require("./assets/stylesheets/nav-bar.scss");

React.render(React.createElement(App), document.body);
