// Generated by CoffeeScript 1.9.3
var MainWindowComponent, NavBarComponent, React, div;

React = require("react");

NavBarComponent = React.createFactory(require("../NavBarComponent"));

MainWindowComponent = React.createFactory(require("../MainWindowComponent"));

div = React.DOM.div;

module.exports = React.createClass({
  displayName: "App",
  render: function() {
    return div({}, NavBarComponent({}), MainWindowComponent({}));
  }
});
