// Generated by CoffeeScript 1.9.3
var React, h1;

React = require("react");

h1 = React.DOM.h1;

module.exports = React.createClass({
  render: function() {
    return h1({
      className: "example-class"
    }, "testing");
  }
});
