// Generated by CoffeeScript 1.9.3
var MainWindowComponent, React, div;

React = require("react");

div = React.DOM.div;

MainWindowComponent = React.createClass({
  displayName: "MainWindowComponent",
  render: function() {
    return div({}, "Main Window Component starts here");
  }
});

module.exports = MainWindowComponent;
