// Generated by CoffeeScript 1.9.3
var Col, Nav, NavBarComponent, Navbar, React, ReactBootstrap, Row, div, h1, ref;

React = require("react");

ReactBootstrap = require("react-bootstrap");

Navbar = React.createFactory(ReactBootstrap.Navbar);

Nav = React.createFactory(ReactBootstrap.Nav);

Row = React.createFactory(ReactBootstrap.Row);

Col = React.createFactory(ReactBootstrap.Col);

ref = React.DOM, div = ref.div, h1 = ref.h1;

NavBarComponent = React.createClass({
  displayName: "NavBarComponent",
  render: function() {
    return Navbar({
      className: "nav-bar"
    }, Nav({}, div({}, h1({
      className: "title"
    }, "Find Me Food"))));
  }
});

module.exports = NavBarComponent;
