// Generated by CoffeeScript 1.9.3
var Col, NavBarComponent, React, ReactBootstrap, Row, div, h1, ref;

React = require("react");

ReactBootstrap = require("react-bootstrap");

Row = React.createFactory(ReactBootstrap.Row);

Col = React.createFactory(ReactBootstrap.Col);

ref = React.DOM, div = ref.div, h1 = ref.h1;

NavBarComponent = React.createClass({
  displayName: "NavBarComponent",
  render: function() {
    return Row({
      className: "nav-bar"
    }, Col({
      md: 8,
      mdOffset: 2
    }, div({}, h1({
      className: "title"
    }, "Find Me Food"))));
  }
});

module.exports = NavBarComponent;
